pipeline {
  environment {
    registry = "engabdullah1909/my-repo"
    registryCredential = 'Docker-Hub-UP'

  }
  agent any

        stages {
            stage('Building image') {
                steps{
                    script {
                    def dockerImage = docker.build("$registry:$env.BUILD_NUMBER")
                    }
            }
            }
            // stage('Deploy Image') {
                // steps{
                    // script {
                        // docker.withRegistry( '', registryCredential ) {
                        // dockerImage.push()
                   // }
                    // }
            // }
            // }
            // stage('Remove Unused docker image') {
                // steps{
                    // sh "docker rmi $registry:$BUILD_NUMBER"
                // }
            // }
        }
}
